services:
  - type: web
    name: liga-oyambarillo
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: liga-data
      mountPath: /data
      sizeGB: 5
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        sync: false
      - key: IMPRENTA_USER
        value: carnets
      - key: IMPRENTA_PASS
        sync: false
      - key: CALIFICACION_USER
        value: comision
      - key: CALIFICACION_PASS
        sync: false
      - key: SANCIONES_USER
        value: sanciones
      - key: SANCIONES_PASS
        sync: false
